import gql from "graphql-tag"

export const getBooking = gql`
query listReservationPagination($page:Int,$pagesize:Int){
    listReservationPagination(page:$page,pagesize:$pagesize){
        totalPage
        totalElement
        reserve{
            id
            aboutYou
            status
            descriptionToKnow
            seatNumber
            reserveDate
            requestingDate
            cancelDate
            reviewEvent{
                id
                rate1
                rate2
                rate3
                rate4
                rate5
                rate6
                rate7
                comment
                chef{
                  id
                }
            }
            user{
                id
                firstName
                lastName
            }
            subevent{
                id
                eventDate
                event{
                    id
                    eventName
                }
            }
            payment{
                id
                paymentMethod
                paymentDate
                refId
                price
                slipUrl
                docUrl
            }
            join{
                id
                firstName
                lastName
            }
        }
    
    }
}
`
export const getReservationById = gql `
query getReservationById($id: Long){
    getReservationById(id:$id){
        id
        aboutYou
        status
        descriptionToKnow
        seatNumber
        reserveDate
        requestingDate
        cancelDate
        refundable
        accountForRefund{
            id
            accountName
            accountNumber
            bankName
            branch
            bankStatementUrl
            dateTimetransfer
            text
            amount
        }
        reviewEvent{
            id
            rate1
            rate2
            rate3
            rate4
            rate5
            rate6
            rate7
            comment
            chef{
              id
            }
        }
        user{
            id
            firstName
            lastName
        }
        subevent{
            id
            startTime
            endTime
            eventDate
            event{
                id
                eventName
                eventType
                eventCategory
                eventDetail
                status
                pricePerSeat
                lat
                lng
                commission
                homeNo
                street
                subDistrict
                district
                city
                postalCode
                startDate
                endDate
                rule
                ownPlace
                requestingDate
                allergic{
                    id
                    allergicName
                }
                subevent{
                    minSeat
                    maxSeat
                    startTime
                    endTime
                    cancelDate
                    eventDate
                    status 
                }
                menu{
                    id
                    foodtype
                    subMenu{
                    id
                    subMenuName
                    subMenuDescription
                    }
                }
                media{
                    id
                    path
                }
                amenitiesPlace{
                    id
                    amenitiesPlaceName
                }
                repeatOn{
                    id
                    repeatOn
                }
                chef{
                    id
                    homeNo
                    street
                    subDistrict
                    district
                    postalCode
                    occupation
                    favoriteCuisine
                    signatureDish
                    passportId
                    passportUrl
                    status
                    acc{
                    id
                    accountName
                    accountNumber
                    bankName
                    branch
                    bankStatementUrl
                    }
                    exp{
                    id
                    cuisineType
                    expYear
                    aboutExp
                    }
                    user{
                    id
                    firstName
                    lastName
                    email
                    gender
                    birthday
                    registeredDate
                    phoneNumber
                    city
                    country
                    nationality
                    profileImage
                    isFacebookUser
                    status
                    aboutMe
                    language{
                        id
                        value
                    }
                    }
                }
            }
        }
        payment{
            id
            paymentMethod
            paymentDate
            refId
            price
            slipUrl
            docUrl
        }
        join{
            id
            firstName
            lastName
            allergic{
                allergicName
            }
        }
    }
}
`
